# 1. Configuração do H2 em Modo Arquivo (salva na raiz do projeto)
spring.datasource.url=jdbc:h2:file:./dados_adega
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilita o painel no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Mostra o SQL no console do IntelliJ (bom para ver o que está acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. O SEGREDO AQUI: Desliga a criação automática do Java e manda ler o seu script
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always